src/main/resources/assets/actuallyadditions/lang/de_DE.lang
Translated up to line 539.
Yet to do: Booklet Chapters
=> [de_DE] First part of booklet

src/main/java/de/ellpeck/actuallyadditions/mod/blocks/base/BlockPlant.java
Basically, I made it so that when you right-click on a fully-grown plant, it will harvest it for you. Y'know, bringing it up to par with other mods in that respect.
=> Added right-click harvest functionality to all crops.

src/main/resources/assets/actuallyadditions/lang/de_DE.lang
yet untranslated lines:
157-186, 429-430, 572-773
=> Matching de_DE.lang with en_US.lang

src/main/resources/assets/actuallyadditions/lang/de_DE.lang
yet untranslated lines:
572-773
=> Translation of ll. 157-186, 429, 430

src/main/java/de/ellpeck/actuallyadditions/mod/material/InitArmorMaterials.java
They changed how it works
//new int[]{boots, leggings, chestplate, helmet}
=> Fixed ArmorMaterial

src/main/resources/assets/actuallyadditions/lang/zh_CN.lang
#1. Update some entries.
#2. fix a lot of errors.
=> Update zh_CN file

src/main/resources/assets/actuallyadditions/lang/zh_CN.lang
=> Update zh_CN to R58

src/main/java/de/ellpeck/actuallyadditions/mod/gen/OreGen.java, src/main/java/de/ellpeck/actuallyadditions/mod/gen/WorldGenLushCaves.java
The code is more complicated than I initially thought it would be due to the size of these structures (this is the reason vanilla water/lava lakes aren't bigger).
Instead of generating lush caves like any other population structure, it instead tries to generate it as if it was starting from each neighbor chunk, and only setting the blocks in currently populated chunk. Exception is setting air to make it possible to generate trees - these have additional 7 block radius, and they have to explicitly ignore any blocks generated there later.
With this change it should be possible to generate lush caves with arbitrarily high frequency/low rarity and it shouldn't crash.
The reason I'm 100% sure it will work with any frequency: I initially made a mistake that caused it either always or never …
=> Fixed recursive/reentrant chunk generation caused by lush caves, closes #275

src/main/java/de/ellpeck/actuallyadditions/mod/config/values/ConfigBoolValues.java, src/main/java/de/ellpeck/actuallyadditions/mod/config/values/ConfigIntListValues.java, src/main/java/de/ellpeck/actuallyadditions/mod/config/values/ConfigIntValues.java, src/main/java/de/ellpeck/actuallyadditions/mod/config/values/ConfigStringListValues.java
The text for some of the configs seems very off. so i decided to go through and fix it up.
=> Redoing text for configs

src/main/java/de/ellpeck/actuallyadditions/mod/booklet/gui/GuiMainPage.java
Changed the name of the quoted player from @KarillEndusa to @YasminEndusa to represent the in-game name change.
=> Changed quoted player @KarillEndusa

src/main/resources/assets/actuallyadditions/lang/en_US.lang, src/main/resources/assets/actuallyadditions/lang/fr_CA.lang, src/main/resources/assets/actuallyadditions/lang/fr_FR.lang
French translations, yay!
Also changed "Carpetet" to "Carpet" and  "charged charged" to "charged" in en_US.lang.
=> Add fr_FR.lang, fr_CA.lang and fix typos in en_US.lang

src/main/java/de/ellpeck/actuallyadditions/mod/event/ClientEvents.java
Wasn't sure whether or not you were actually interested on fixing this. So I tested doing this little addition and it seems to work perfectly! Should solve #701.
Hopefully you're ok with merging it, for us boring people :^)
=> Corrected HWYLA/WAILA support on boring mode, solves #701

src/main/java/de/ellpeck/actuallyadditions/mod/blocks/BlockColoredLamp.java
Align lamps properly with docs
Make light updates smoother as well, and use a better access to the needed blockstate.
=> Closes #816 and #819

src/main/java/de/ellpeck/actuallyadditions/mod/jei/JEIActuallyAdditionsPlugin.java, src/main/java/de/ellpeck/actuallyadditions/mod/jei/compost/CompostRecipeCategory.java, src/main/java/de/ellpeck/actuallyadditions/mod/jei/compost/CompostRecipeWrapper.java, src/main/java/de/ellpeck/actuallyadditions/mod/tile/TileEntityCompost.java
Hi there,
I used the nei_simple GUI template and made a JEI interface for the Compost, let me know if you've got any suggestions to make it look nicer. Addresses issue #791. 
Also, it looks like this:
=> Added Compost recipes to JEI (Closes #791)

src/main/resources/assets/actuallyadditions/lang/it_IT.lang
=> Added Italian localization

src/main/java/de/ellpeck/actuallyadditions/mod/booklet/gui/GuiMainPage.java
Because Using my old username is so 2010.
=> Updated My own name to reflect new username

src/main/java/de/ellpeck/actuallyadditions/mod/items/ItemSolidifiedExperience.java
Fix solid experience dropping when doMobLoot is set to false
=> Closes Ellpeck#1230

src/main/resources/assets/actuallyadditions/lang/de_DE.lang
Updated the german language file to latest version and translated everything but the manual pages.
=> Updated german translation

build.gradle, src/main/java/de/ellpeck/actuallyadditions/mod/blocks/render/RenderBatteryBox.java, src/main/java/de/ellpeck/actuallyadditions/mod/inventory/gui/EnergyDisplay.java, src/main/java/de/ellpeck/actuallyadditions/mod/items/base/ItemEnergy.java, update/changelog.md
Signed-off-by: Cranky Supertoon <crankysupertoon@gmail.com>
=> Crystal Flux Localization

src/main/java/de/ellpeck/actuallyadditions/mod/tile/TileEntityCoffeeMachine.java
A simple fix for coffee maker not accepting empty cups though automation.
=> Coffee Maker automation fix
